services:
  postgres:
    image: postgres:latest
    container_name: frota-postgres-db
    environment:
      POSTGRES_USER: sergipetec
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: frota
    ports:
      - "5432:5432"
    networks:
      - frota-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: frota-backend
    volumes:
      - ./backend:/app:cached
    command: mvn spring-boot:run
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/frota
      SPRING_DATASOURCE_USERNAME: sergipetec
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    networks:
      - frota-network

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: frota-frontend
  #   ports:
  #     - "5173:5173"
  #   networks:
  #     - frota-network
  #   depends_on:
  #     - backend
  #   volumes:
  #     - ./frontend:/app:cached

networks:
  frota-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
